### PR TITLE
Seperate Beginner's and Modder/Developer's Guides

### PR DESCRIPTION
**Pull request by Xilophor**
Separated the two guides - as mentioned in #47 - each having separate content aside from the About page. It's not complete yet as I've got to write the intro article to the Developer's Guide.

Due to that, I'm opening this as a Draft PR, since I want some input on what I've done so far - especially with how I did the duplicate `About` pages. Just don't want to make further changes before anything may be reverted :)

Will try to finish this by tomorrow; I want to get this out soon so we have a (hopefully) finished standard of creating/implementing new articles for any new contributors.

### CODE REVIEW

**Comment by Xilophor** [comment]
Planning on moving all the markdown files to a src folder to prevent people from accessing lethal.wiki/[about] as it's not a wanted url, but that has the potential of breaking things on the hosting end, so I'll leave that decision up to you @legoandmars

**Comment by legoandmars** [comment]
Honestly I think I'd prefer `about` just redirecting to the wrong sidebar, I think that and the translation one will be the only cross-sidebar pages

FAQ can be moved to the specific modding/development sections

Ideally we wouldn't move the source file directory any more just to make hosting and translations simpler (there's still some weirdness with translations I need to fix)

Having multiple about pages will probably increase complexity & make SEO slightly worse since it's a static site, it's just building the same page twice in different locations which might get a little weird

**Comment by legoandmars** [comment]
I would probably also create a new `developers-guide.md` page that's more of an overview (and in the root of /docs) just to stay consistent

Otherwise looks good so far though, the new sidebars are much easier to read, and the extra button at the top should make things fairly easy to find

**Comment by legoandmars** [comment]
> Honestly I think I'd prefer `about` just redirecting to the wrong sidebar, I think that and the translation one will be the only cross-sidebar pages

We could also just add it to the top bar maybe, not sure how crowded it will get though

**Comment by Xilophor** [comment]
> I would probably also create a new `developers-guide.md` page that's more of an overview (and in the root of /docs) just to stay consistent

Currently working on an Dev Guide overview page, but in order to make it appear in the Dev Guide sidebar, I have to have it in the `/modding/` folder, otherwise it'll only appear in the Beginner's Guide sidebar

**Comment by Xilophor** [comment]
I was considering putting the Beginner's Guide in a folder, but decided against it. IMO, it's more important for people installing mods to have an easier to understand url thaan for modders (who ideally have some techy knowledge).

**Comment by Xilophor** [comment]
> Honestly I think I'd prefer `about` just redirecting to the wrong sidebar, I think that and the translation one will be the only cross-sidebar pages
> 
> FAQ can be moved to the specific modding/development sections
> 
> Ideally we wouldn't move the source file directory any more just to make hosting and translations simpler (there's still some weirdness with translations I need to fix)
> 
> Having multiple about pages will probably increase complexity & make SEO slightly worse since it's a static site, it's just building the same page twice in different locations which might get a little weird
> 

Okay, I'll update it accordingly

**Comment by Xilophor** [comment]
> > Honestly I think I'd prefer `about` just redirecting to the wrong sidebar, I think that and the translation one will be the only cross-sidebar pages
> 
> We could also just add it to the top bar maybe, not sure how crowded it will get though

If we ever need to add anything else to the top bar, we can always add it as a drop-down section with the text & links

**Comment by legoandmars** [comment]
ooc is there any easy (intended) way to do redirects with vitepress? i would like to preserve `https://lethal.wiki/beginners-guide` if possible

If it's not easy to do, it's not a massive deal. Some of the pages moving (and making old URLs incorrect) will be a little annoying but overall it's probably a better choice in the long run

**Comment by legoandmars** [comment]
obviously this needs to be updated for the other PRs (custom configs/contributing guides), but looks good to me

I'll wait to see if @MaxWasUnavailable has any feedback before approving

**Comment by Xilophor** [comment]
> ooc is there any easy (intended) way to do redirects with vitepress? i would like to preserve `https://lethal.wiki/beginners-guide` as a redirect if possible
> 
> If it's not easy to do, it's not a massive deal. Some of the pages moving (and making old URLs incorrect) will be a little annoying but overall it's probably a better choice in the long run, I like the new structure better

iirc there's an html tag for that, will look into it

**Comment by MaxWasUnavailable** [comment]
Perhaps `Beginner` needs to be `User`?

Beginner's Guide --> User's Guide

**Comment by Xilophor** [comment]
> > ooc is there any easy (intended) way to do redirects with vitepress? i would like to preserve `https://lethal.wiki/beginners-guide` as a redirect if possible
> > If it's not easy to do, it's not a massive deal. Some of the pages moving (and making old URLs incorrect) will be a little annoying but overall it's probably a better choice in the long run, I like the new structure better
> 
> iirc there's an html tag for that, will look into it

@legoandmars In testing I was able to get `/beginners-guide.html` to redirect, but not `/beginners-guide`, however if your hosting service allows for clean urls it might work anyways (assuming the url w/o the extension is silently redirected)

**Comment by Xilophor** [comment]
> Perhaps `Beginner` needs to be `User`?
> 
> Beginner's Guide --> User's Guide

Yes and no.

It would make more sense to be `User's Guide`; however, if you're coming in as someone who's never installed a mod before, would `Beginner's Guide` or `User's Guide` make more sense? IMO, `Beginner's Guide` makes more sense for new users.

Although, this comes down more to semantics, as either one would be the only guide outside of `Developer's Guide`

**Comment by MaxWasUnavailable** [comment]
Perhaps `Beginner` needs to be `User`?

Beginner's Guide --> User's Guide

> > Perhaps `Beginner` needs to be `User`?
> > Beginner's Guide --> User's Guide
> 
> Yes and no.
> 
> It would make more sense to be `User's Guide`; however, if you're coming in as someone who's never installed a mod before, would `Beginner's Guide` or `User's Guide` make more sense? IMO, `Beginner's Guide` makes more sense for new users.
> 
> Although, this comes down more to semantics, as either one would be the only guide outside of `Developer's Guide`

I feel like it's moreso the comparison between "Beginner & Developer", that might confuse users into thinking it's for "beginner modders" and "IRL developer modders". Whereas User vs Developer is a fairly clear distinction.

**Comment by legoandmars** [comment]
> It would make more sense to be `User's Guide`; however, if you're coming in as someone who's never installed a mod before, would `Beginner's Guide` or `User's Guide` make more sense? IMO, `Beginner's Guide` makes more sense for new users.
> 
> Although, this comes down more to semantics, as either one would be the only guide outside of `Developer's Guide`


I also prefer beginner's guide just because it makes it more immediately obvious to people who have never installed mods

> I feel like it's moreso the comparison between "Beginner & Developer", that might confuse users into thinking it's for "beginner modders" and "IRL developer modders". Whereas User vs Developer is a fairly clear distinction.


This could be a slight problem but IMO it would make things slightly more unclear for users 
I think in the end developers are going to be much more adaptable

**Comment by legoandmars** [comment]
Even if a modder goes to the beginner's guide first, it does have a basic section on creating mods (and redirects you to the correct place)

**Comment by legoandmars** [comment]
> @legoandmars In testing I was able to get `/beginners-guide.html` to redirect, but not `/beginners-guide`, however if your hosting service allows for clean urls it might work anyways (assuming the url w/o the extension is silently redirected)

I have no idea if this will work, worst case we revert that specific feature

**Comment by Xilophor** [comment]
> > @legoandmars In testing I was able to get `/beginners-guide.html` to redirect, but not `/beginners-guide`, however if your hosting service allows for clean urls it might work anyways (assuming the url w/o the extension is silently redirected)
> 
> I have no idea if this will work, worst case we revert that specific feature

Worst case it only works for `/beginners-guide.html`; it shouldn't create any issues

**Comment by Xilophor** [comment]
> > @legoandmars In testing I was able to get `/beginners-guide.html` to redirect, but not `/beginners-guide`, however if your hosting service allows for clean urls it might work anyways (assuming the url w/o the extension is silently redirected)
> 
> I have no idea if this will work, worst case we revert that specific feature

Just have to test in prod :)

**Comment by Xilophor** [comment]
Thought I had, but want y'alls opinions on this; should we rename Advanced Topics to just Topics? (also would rename `/advanced` to `/topics`)

**Review by legoandmars — APPROVED** [review]

**Pull request merged**
