### PR TITLE
r2modman profile sharing

### PR DESCRIPTION
**Pull request by ghotato**
added a "How-to" for sharing profiles so thunderstore isnt swamped with modpacks made for small friend groups

### CODE REVIEW

**Review by Boxofbiscuits97 — COMMENTED** [review]
## This is a great push to add for helping players. 
However I do not feel it aligns with the style nor hold actual direction in the same format as the rest of the wiki. I've created some more robust screenshots for directions if you wouldn't mind. There are also some parts of this such as selecting the game that seem a tad redundant. I don't mind taking over if you don't feel like going through the hassle of fulfilling this PR in it's entirety since I've been working on docs for this myself but have yet to make a PR myself.

**Comment by Boxofbiscuits97** [comment]
See [my PR](https://github.com/LethalCompany/ModdingWiki/pull/31) for a better implementation

**Comment by ghotato** [comment]
> ## This is a great push to add for helping players.
> However I do not feel it aligns with the style nor hold actual direction in the same format as the rest of the wiki. I've created some more robust screenshots for directions if you wouldn't mind. There are also some parts of this such as selecting the game that seem a tad redundant. I don't mind taking over if you don't feel like going through the hassle of fulfilling this PR in it's entirety since I've been working on docs for this myself but have yet to make a PR myself.

i was trying to break it down barney style just in case you know?

**Comment by ghotato** [comment]
see biscuits PR

**Pull request closed without merging**
