### PR TITLE
Describe additional r2modman features (config, profile codes)

### PR DESCRIPTION
**Pull request by legoandmars**
- Migrate profile code section to a new page
- Add a configuration page that details how to change mod configs in r2modman (thanks for writing @Boxofbiscuits97)

### CODE REVIEW

**Review by Boxofbiscuits97 — APPROVED** [review]
W pr, add it.
### Add it now

**Comment by Boxofbiscuits97** [comment]
Change the **Syncing r2modman profiles** to **Sharing r2modman profiles**

**Review by Boxofbiscuits97 — APPROVED** [review]
Is it done yet?
## Yes

**Review by Boxofbiscuits97 — CHANGES_REQUESTED** [review]
Spelling mistake. In the vitepress config there's an extra comma

**Review by MaxWasUnavailable — APPROVED** [review]

**Pull request merged**
