### PR TITLE
Migrate framework to VitePress

### PR DESCRIPTION
**Pull request by legoandmars**
There's a few things about docsify that have been personally bothering me and (IMO) are hampering the wiki a bit. There's some details in #12 and #26.

Basically:
- SEO is not great, and we're only limited to the default page for SEO and embeds
- Docsify isn't super modern, and these problems aren't fixable without migrating frameworks
- Adding new things (like search) is going to be significantly more complicated than it should be using Docsify

This PR converts the wiki to use VitePress, a similar framework that also uses .md files
There were minimal markdown-changes that had to be made, I simply
- Added description/navigation metadata to pages
- Moved from old warning/infobox system (`! >`) to vitepress's formatting (`::: warning`)

This will make embeds look significantly better, and help the site a LOT on google rankings, hopefully getting the wiki recommended instead of random outdated articles

Here's a preview of how the new styling looks:
firefox_mnP3rMsOLn

Embeds also look significantly better now, here's before and after (notice how each linked page will now actually show proper page-specific metadata)

firefox_1hcvVwStwH

This also adds the following features:
- Search box to easily find specific pages
- "Edit this page" button at the bottom of each page that links to a convenient GitHub editor 
- New beginners guide page

### CODE REVIEW

**Comment by legoandmars** [comment]
This PR is feature complete except for:
- Live Thunderstore version
- Translation
- automatic CI deployment

all of which I will be added to this PR shortly

if you'd like to preview the new wiki locally run `npm i` then `npm run docs:dev`

**Comment by legoandmars** [comment]
I would love any specific thoughts on this @MaxWasUnavailable @Xilophor. I have tried to make the transition as smooth as possible: hosting and writing new articles should be essentially identical

Contributing should also be more directly accessible with the "Edit this page" button. I'd like to write up a [contributing guide like bsmg.wiki has](https://docs.google.com/document/d/1r6IP6l3uo8rc__GxfLkpaToxheeXotdYaKEj3oWB2js/edit) at some point

**Comment by MaxWasUnavailable** [comment]
> Adding new things (like search) is going to be significantly more complicated than it should be using Docsify

Docsify already has a search, which seems to work fine. Could you elaborate?

**Comment by MaxWasUnavailable** [comment]
> This PR is feature complete except for:
> 
>     * Live Thunderstore version system
> 
>     * Translation
> 
>     * automatic CI deployment
> 
> 
> all of which I will be added to this PR shortly
> 
> if you'd like to preview the new wiki locally run `npm i` then `npm run docs:dev`

What do you mean by `Live Thunderstore version system`?

**Comment by Xilophor** [comment]
After quickly going through a local preview, it looks and feels significantly better than the docsify version. I'm happy that this process allows better SEO. From the article writing side, I'm glad that it's virtually identical.

> What do you mean by `Live Thunderstore version system`?

This, no?
image

**Comment by legoandmars** [comment]
> > Adding new things (like search) is going to be significantly more complicated than it should be using Docsify
> 
> Docsify already has a search, which seems to work fine. Could you elaborate?

Ah yeah I dropped a word there, I specifically meant [Algolia search](https://www.algolia.com) so we can have more relevant search than just "search the exact phrase"

What docsify has works alright, but I do think having something that supports synonyms/more complicated queries would be nice, especially as the site grows

**Comment by legoandmars** [comment]
> What do you mean by `Live Thunderstore version system`?

The r2modman page runs a query to thunderstore to get the latest r2modman version, I just need to reimplement it for the new framework

Honestly we might want to remove this at some point, it's fairly minor and I don't want to accidentally burden thunderstore with traffic - i'll probably make an issue later

**Comment by Xilophor** [comment]
> > Adding new things (like search) is going to be significantly more complicated than it should be using Docsify
> 
> Docsify already has a search, which seems to work fine. Could you elaborate?

Docsify did have a search function, although it doesn't seem great.
image

Looking at the exact same search in the new one, it gives a much better preview (if enabled).
image

> Ah yeah I dropped a word there, I specifically meant [Algolia search](https://www.algolia.com/) so we can have more relevant search than just "search the exact phrase"

Looking at a potential search, it does seem to better support/sort based on complicated searches that don't exactly match the content. Example search: `how do I load the network object into the scene`

Docsify
image

VitePress
image

**Comment by legoandmars** [comment]
Right now it's just using vitepress's (solid) local search, but once it's deployed and had some time to simmer I'll try to set it up with Algolia, which should be even better

**Comment by Xilophor** [comment]
> Right now it's just using vitepress's (solid) local search, but once it's deployed and had some time to simmer I'll try to set it up with Algolia, which should be even better

If that's just the local search, I can't wait to see what Algolia looks like. Any timeline on when you plan to add that as a PR/to this PR?

**Comment by legoandmars** [comment]
> If that's just the local search, I can't wait to see what Algolia looks like. Any timeline on when you plan to add that as a PR/to this PR?

One of the people I consulted with about frameworks specifically said it's a bit of a process to set up, so it'll probably be a week or two

**Comment by legoandmars** [comment]
> The r2modman page runs a query to thunderstore to get the latest r2modman version, I just need to reimplement it for the new framework
> 
> Honestly we might want to remove this at some point, it's fairly minor and I don't want to accidentally burden thunderstore with massive amounts of traffic - i'll probably make an issue later

I've just removed this for now. It's neat but I'm worried it's not helping with the thunderstore downtime

I'll look into doing it on build time in a separate PR

**Comment by legoandmars** [comment]
Translation also needs to be fixed in a separate PR because I think the only way to get crowdin to register the new changes is pulling them into main

**Comment by MaxWasUnavailable** [comment]
Looks superb! Great work @legoandmars

**Review by MaxWasUnavailable — APPROVED** [review]

**Pull request merged**
